### ISSUE TITLE
Vision and Language

### ISSUE THREAD

**Issue by kmario23** [eugeneyan/ml-surveys#5]
Hey @eugeneyan,
  Thanks for creating & maintaining this. I think it'd be useful to include a topic on **Vision & Language** and I'd like to suggest a few papers already.

 1) [Trends in Integration of Vision and Language Research: A Survey of Tasks, Datasets, and Methods](https://arxiv.org/abs/1907.09358)
 2) [Multimodal Research in Vision and Language: A Review of Current and Emerging Trends](https://arxiv.org/abs/2010.09522)

**Comment by eugeneyan** [comment]
Thanks @kmario23! Those are great suggestions. Would you like to make a pull requests? Or should I do it on your behalf?

**Comment by kmario23** [comment]
PR, done!
